version: "3.5"

services:
  backend-admin:
    container_name: backend-admin
    restart: always
    image: backend-admin
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
