version: "3"
services:
  mongodb:
    container_name: marketplace_mongo
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - common
  cache:
    container_name: marketplace_redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
    networks:
      - common

volumes:
  dbdata6:
  cache:

networks:
  common:
    driver: bridge
